### ISSUE TITLE
[Bug] 导出时出现IO错误

### ISSUE THREAD

**Issue by Embers-of-the-Fire** [soarteam/SuperSpineViewer#45]
## 概述

在使用2.1.0版release jar包时，可以正常导入、预览spine骨骼，但是无法导出。

## 具体操作

在导出页面，无论选择什么导出格式或导出质量，在点击导出按钮后会出现java lang io错误。

<details>
<summary>日志</summary>

```text
1月 22, 2024 3:03:18 下午 com.sun.javafx.application.PlatformImpl startup
警告: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @c04a8eb'
SuperSpineViewer已启动
Spine二进制版本：36
请求初始化
请求：开始录制
java.io.IOException: 系统找不到指定的路径。
        at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:536)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at to.aloen.ssv.RecordFX.writePNG(RecordFX.java:152)
        at to.aloen.ssv.RecordFX$Task.run(RecordFX.java:181)
        at to.aloen.ssv.RecordFX$1.lambda$new$0(RecordFX.java:25)
        at java.base/java.lang.Thread.run(Thread.java:1583)
java.io.IOException: 系统找不到指定的路径。
        at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:536)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at to.aloen.ssv.RecordFX.writePNG(RecordFX.java:152)
        at to.aloen.ssv.RecordFX$Task.run(RecordFX.java:181)
        at to.aloen.ssv.RecordFX$1.lambda$new$0(RecordFX.java:25)
        at java.base/java.lang.Thread.run(Thread.java:1583)
# 以下为重复产生的错误信息
```

</details>

## 参考错误源

`ssv/RecordFX.java`, line 81, 87 and 150.

```java
STR."\{Main.outPath}\{fileName}_Sequence\{File.separator}\{fileName}_\{index}.png"
```

疑似 `outPath` 与 `fileName` 间缺少间隔符导致视作为一个文件夹名。

同时无法修改缓存目录，导致即使手动创建文件夹也会出现在 `Users/` 目录下导致权限出错，原因未定位。

## 备注

确保使用 jdk-21，已安装ffmpeg。

```text
PS C:\Users\Admin> java --version
java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

PS C:\Users\Admin> ffmpeg -version
ffmpeg version 6.1.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100
```

**Comment by Embers-of-the-Fire** [comment]
好了，鉴定完毕，文件路径的 `outPath` 和缓存文件夹名之间确实加一个 `File.separator` 就好了

**Comment by Aloento** [comment]
选择文件夹的时候默认会在最后面加一个/，这个/不能少
